name: ustropralki
description: Ustro Pralki Flutter Mobile App

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.0+6

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Add the dependency for the Firebase Core Flutter SDK
  firebase_core: ^1.17.1
  # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^9.1.9
  cloud_firestore: ^3.1.17
  google_sign_in: ^5.3.2
  firebase_auth: ^3.3.19
  flutter_countdown_timer: ^4.1.0
  firebase_messaging: ^11.4.1
  flutter_local_notifications: ^9.6.1
  mobile_scanner: ^2.0.0
  shared_preferences: ^2.0.15
  auto_size_text: ^3.0.0
  flutter_svg: ^1.1.0
  permission_handler: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - res/languages/pl.json
    - res/languages/en.json
    - res/ustro_logo.png
    - res/logo_ustropralki.png
    - res/loading_bg.png
    - res/logo_g.png
    - res/logout.svg
    - res/check.svg



  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
